// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChDHJO2lN5h8ssTBHu1Wr1drcriQg02kg',
    appId: '1:813791190074:web:1dc0f34742666cfd3c2903',
    messagingSenderId: '813791190074',
    projectId: 'cartkaro-e2ea7',
    authDomain: 'cartkaro-e2ea7.firebaseapp.com',
    storageBucket: 'cartkaro-e2ea7.firebasestorage.app',
    measurementId: 'G-R5XL0J6999',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn8uS1pBEpKNmmQ-3TWY3j3p-BiRz5RJI',
    appId: '1:813791190074:android:4c79be2654fe29f13c2903',
    messagingSenderId: '813791190074',
    projectId: 'cartkaro-e2ea7',
    storageBucket: 'cartkaro-e2ea7.firebasestorage.app',
  );

}