final Map<String, List<Map<String, dynamic>>> restaurantData = {
  'Top Picks': [
    {'id': 'r1', 'name': 'Chicken Dum Biryani', 'brand': 'Biryani Blues', 'image': 'assets/images/burger.png', 'isBestseller': true, 'restaurant': 'Biryani Blues', 'rating': '4.7', 'time': '35-40 Mins', 'distance': '3.5 km', 'totalSells': '25K+ orders', 'isVeg': false, 'price': 160.0, 'weight': 'Half', 'variants': [{'weight': 'Half', 'price': 160.0, 'originalPrice': 199.0}, {'weight': 'Full', 'price': 280.0, 'originalPrice': 349.0}]},
    {'id': 'r2', 'name': 'Farmhouse Veg Pizza', 'brand': 'Domino\'s Pizza', 'image': 'assets/images/broccoli.png', 'restaurant': 'Domino\'s Pizza', 'rating': '4.3', 'time': '20-25 Mins', 'distance': '2.1 km', 'totalSells': '50K+ orders', 'isVeg': true, 'price': 199.0, 'weight': 'Regular', 'variants': [{'weight': 'Regular', 'price': 199.0, 'originalPrice': 249.0}, {'weight': 'Medium', 'price': 399.0, 'originalPrice': 499.0}]},
    {'id': 'r3', 'name': 'Veg Steam Momos', 'brand': 'Momo Corner', 'image': 'assets/images/broccoli.png', 'isBestseller': true, 'restaurant': 'Momo Corner', 'rating': '4.6', 'time': '15-20 Mins', 'distance': '1.8 km', 'totalSells': '15K+ orders', 'isVeg': true, 'price': 80.0, 'weight': '6 pcs', 'variants': [{'weight': '6 pcs', 'price': 80.0, 'originalPrice': 110.0}, {'weight': '10 pcs', 'price': 120.0, 'originalPrice': 160.0}]},
    {'id': 'r21', 'name': 'Chole Bhature', 'brand': 'Haldiram\'s', 'image': 'assets/images/broccoli.png', 'isBestseller': true, 'restaurant': 'Haldiram\'s', 'rating': '4.5', 'time': '30 Mins', 'distance': '2.2 km', 'totalSells': '35K+ orders', 'isVeg': true, 'price': 150.0, 'weight': '1 Plate', 'variants': [{'weight': '1 Plate (2 pcs)', 'price': 150.0, 'originalPrice': 180.0}]},
  ],
  'Trending': [
    {'id': 'r4', 'name': 'Zinger Chicken Burger', 'brand': 'Burger King', 'image': 'assets/images/burger.png', 'isBestseller': true, 'restaurant': 'Burger King', 'rating': '4.5', 'time': '25-30 Mins', 'distance': '1.2 km', 'totalSells': '10K+ orders', 'isVeg': false, 'price': 149.0, 'weight': '1 pc', 'variants': [{'weight': '1 pc', 'price': 149.0, 'originalPrice': 189.0}, {'weight': 'Combo', 'price': 249.0, 'originalPrice': 310.0}]},
    {'id': 'r5', 'name': 'Veg Hakka Noodles', 'brand': 'Chowman', 'image': 'assets/images/broccoli.png', 'restaurant': 'Chowman', 'rating': '4.2', 'time': '30 Mins', 'distance': '4.0 km', 'totalSells': '8K+ orders', 'isVeg': true, 'price': 90.0, 'weight': 'Half', 'variants': [{'weight': 'Half', 'price': 90.0, 'originalPrice': 120.0}, {'weight': 'Full', 'price': 150.0, 'originalPrice': 199.0}]},
    {'id': 'r6', 'name': 'Classic Cold Coffee', 'brand': 'Cafe Coffee Day', 'image': 'assets/images/broccoli.png', 'isBestseller': true, 'restaurant': 'Cafe Coffee Day', 'rating': '4.6', 'time': '20 Mins', 'distance': '2.5 km', 'totalSells': '12K+ orders', 'isVeg': true, 'price': 120.0, 'weight': 'Regular', 'variants': [{'weight': 'Regular', 'price': 120.0, 'originalPrice': 150.0}, {'weight': 'Large', 'price': 180.0, 'originalPrice': 220.0}]},
    {'id': 'r22', 'name': 'Chicken Egg Roll', 'brand': 'Kolkata Rolls', 'image': 'assets/images/broccoli.png', 'restaurant': 'Kolkata Rolls', 'rating': '4.4', 'time': '15-20 Mins', 'distance': '1.0 km', 'totalSells': '18K+ orders', 'isVeg': false, 'price': 80.0, 'weight': '1 pc', 'variants': [{'weight': '1 pc', 'price': 80.0, 'originalPrice': 100.0}, {'weight': 'Double Egg Chicken', 'price': 120.0, 'originalPrice': 140.0}]},
  ],
  'Top Cuisines': [
    {'id': 'r7', 'name': 'Butter Chicken', 'brand': 'Punjabi Dhaba', 'image': 'assets/images/broccoli.png', 'isBestseller': true, 'restaurant': 'Punjabi Dhaba', 'rating': '4.4', 'time': '40 Mins', 'distance': '3.0 km', 'totalSells': '18K+ orders', 'isVeg': false, 'price': 320.0, 'weight': 'Half', 'variants': [{'weight': 'Half', 'price': 320.0, 'originalPrice': 380.0}, {'weight': 'Full', 'price': 550.0, 'originalPrice': 650.0}]},
    {'id': 'r8', 'name': 'Paneer Butter Masala', 'brand': 'Punjabi Dhaba', 'image': 'assets/images/broccoli.png', 'restaurant': 'Punjabi Dhaba', 'rating': '4.4', 'time': '40 Mins', 'distance': '3.0 km', 'totalSells': '18K+ orders', 'isVeg': true, 'price': 220.0, 'weight': 'Half', 'variants': [{'weight': 'Half', 'price': 220.0, 'originalPrice': 260.0}, {'weight': 'Full', 'price': 380.0, 'originalPrice': 450.0}]},
    {'id': 'r9', 'name': 'Masala Dosa', 'brand': 'South Indian Hub', 'image': 'assets/images/broccoli.png', 'isBestseller': true, 'restaurant': 'South Indian Hub', 'rating': '4.8', 'time': '25 Mins', 'distance': '1.5 km', 'totalSells': '30K+ orders', 'isVeg': true, 'price': 110.0, 'weight': '1 pc', 'variants': [{'weight': '1 pc', 'price': 110.0, 'originalPrice': 140.0}]},
    {'id': 'r10', 'name': 'Chilli Chicken', 'brand': 'Chowman', 'image': 'assets/images/broccoli.png', 'restaurant': 'Chowman', 'rating': '4.2', 'time': '30 Mins', 'distance': '4.0 km', 'totalSells': '8K+ orders', 'isVeg': false, 'price': 180.0, 'weight': 'Half', 'variants': [{'weight': 'Half', 'price': 180.0, 'originalPrice': 220.0}, {'weight': 'Full', 'price': 320.0, 'originalPrice': 380.0}]},
    {'id': 'r20', 'name': 'Authentic Litti Chokha', 'brand': 'Bansi Vihar', 'image': 'assets/images/broccoli.png', 'isBestseller': true, 'restaurant': 'Bansi Vihar', 'rating': '4.8', 'time': '30 Mins', 'distance': '2.5 km', 'totalSells': '20K+ orders', 'isVeg': true, 'price': 120.0, 'weight': '2 pcs', 'variants': [{'weight': '2 pcs', 'price': 120.0, 'originalPrice': 150.0}, {'weight': '4 pcs', 'price': 220.0, 'originalPrice': 280.0}]},
    {'id': 'r23', 'name': 'Dal Makhani', 'brand': 'Punjabi Dhaba', 'image': 'assets/images/broccoli.png', 'restaurant': 'Punjabi Dhaba', 'rating': '4.5', 'time': '40 Mins', 'distance': '3.0 km', 'totalSells': '12K+ orders', 'isVeg': true, 'price': 180.0, 'weight': 'Half', 'variants': [{'weight': 'Half', 'price': 180.0, 'originalPrice': 210.0}, {'weight': 'Full', 'price': 310.0, 'originalPrice': 360.0}]},
  ],
  'Biryani & Pulao': [
    {'id': 'r11', 'name': 'Hyderabadi Chicken Biryani', 'brand': 'Biryani Blues', 'image': 'assets/images/broccoli.png', 'isBestseller': true, 'restaurant': 'Biryani Blues', 'rating': '4.7', 'time': '35-40 Mins', 'distance': '3.5 km', 'totalSells': '25K+ orders', 'isVeg': false, 'price': 180.0, 'weight': 'Half', 'variants': [{'weight': 'Half', 'price': 180.0, 'originalPrice': 230.0}, {'weight': 'Full', 'price': 320.0, 'originalPrice': 399.0}]},
    {'id': 'r12', 'name': 'Mutton Dum Biryani', 'brand': 'Biryani Blues', 'image': 'assets/images/broccoli.png', 'restaurant': 'Biryani Blues', 'rating': '4.7', 'time': '35-40 Mins', 'distance': '3.5 km', 'totalSells': '25K+ orders', 'isVeg': false, 'price': 399.0, 'weight': 'Full', 'variants': [{'weight': 'Full', 'price': 399.0, 'originalPrice': 480.0}, {'weight': 'Family Pack', 'price': 750.0, 'originalPrice': 899.0}]},
    {'id': 'r13', 'name': 'Veg Pulao with Raita', 'brand': 'Haldiram\'s', 'image': 'assets/images/broccoli.png', 'restaurant': 'Haldiram\'s', 'rating': '4.5', 'time': '30 Mins', 'distance': '2.2 km', 'totalSells': '20K+ orders', 'isVeg': true, 'price': 160.0, 'weight': 'Full', 'variants': [{'weight': 'Full', 'price': 160.0, 'originalPrice': 199.0}]},
    {'id': 'r24', 'name': 'Egg Dum Biryani', 'brand': 'Biryani Blues', 'image': 'assets/images/broccoli.png', 'restaurant': 'Biryani Blues', 'rating': '4.4', 'time': '35-40 Mins', 'distance': '3.5 km', 'totalSells': '10K+ orders', 'isVeg': false, 'price': 140.0, 'weight': 'Half', 'variants': [{'weight': 'Half (2 Eggs)', 'price': 140.0, 'originalPrice': 180.0}, {'weight': 'Full (4 Eggs)', 'price': 240.0, 'originalPrice': 299.0}]},
  ],
  'Pizzas & Burgers': [
    {'id': 'r14', 'name': 'Cheese Burst Margherita', 'brand': 'Domino\'s Pizza', 'image': 'assets/images/broccoli.png', 'isBestseller': true, 'restaurant': 'Domino\'s Pizza', 'rating': '4.3', 'time': '20-25 Mins', 'distance': '2.1 km', 'totalSells': '50K+ orders', 'isVeg': true, 'price': 149.0, 'weight': 'Regular', 'variants': [{'weight': 'Regular', 'price': 149.0, 'originalPrice': 189.0}, {'weight': 'Medium', 'price': 299.0, 'originalPrice': 359.0}]},
    {'id': 'r15', 'name': 'Crunchy Chicken Burger', 'brand': 'Burger King', 'image': 'assets/images/burger.png', 'restaurant': 'Burger King', 'rating': '4.5', 'time': '25-30 Mins', 'distance': '1.2 km', 'totalSells': '10K+ orders', 'isVeg': false, 'price': 129.0, 'weight': '1 pc', 'variants': [{'weight': '1 pc', 'price': 129.0, 'originalPrice': 159.0}]},
    {'id': 'r16', 'name': 'Spicy Paneer Tikka Burger', 'brand': 'Burger King', 'image': 'assets/images/broccoli.png', 'isBestseller': true, 'restaurant': 'Burger King', 'rating': '4.5', 'time': '25-30 Mins', 'distance': '1.2 km', 'totalSells': '10K+ orders', 'isVeg': true, 'price': 119.0, 'weight': '1 pc', 'variants': [{'weight': '1 pc', 'price': 119.0, 'originalPrice': 149.0}, {'weight': 'Combo', 'price': 169.0, 'originalPrice': 210.0}]},
    {'id': 'r25', 'name': 'Chicken Pepperoni Pizza', 'brand': 'Domino\'s Pizza', 'image': 'assets/images/broccoli.png', 'isBestseller': true, 'restaurant': 'Domino\'s Pizza', 'rating': '4.6', 'time': '20-25 Mins', 'distance': '2.1 km', 'totalSells': '30K+ orders', 'isVeg': false, 'price': 319.0, 'weight': 'Regular', 'variants': [{'weight': 'Regular', 'price': 319.0, 'originalPrice': 389.0}, {'weight': 'Medium', 'price': 549.0, 'originalPrice': 650.0}]},
  ],
  'Noodles & Momos': [
    {'id': 'r17', 'name': 'Chicken Hakka Noodles', 'brand': 'Chowman', 'image': 'assets/images/broccoli.png', 'isBestseller': true, 'restaurant': 'Chowman', 'rating': '4.2', 'time': '30 Mins', 'distance': '4.0 km', 'totalSells': '8K+ orders', 'isVeg': false, 'price': 110.0, 'weight': 'Half', 'variants': [{'weight': 'Half', 'price': 110.0, 'originalPrice': 140.0}, {'weight': 'Full', 'price': 190.0, 'originalPrice': 240.0}]},
    {'id': 'r18', 'name': 'Chicken Steam Momos', 'brand': 'Momo Corner', 'image': 'assets/images/broccoli.png', 'restaurant': 'Momo Corner', 'rating': '4.6', 'time': '15-20 Mins', 'distance': '1.8 km', 'totalSells': '15K+ orders', 'isVeg': false, 'price': 99.0, 'weight': '6 pcs', 'variants': [{'weight': '6 pcs', 'price': 99.0, 'originalPrice': 130.0}, {'weight': '10 pcs', 'price': 149.0, 'originalPrice': 199.0}]},
    {'id': 'r19', 'name': 'Veg Fried Momos', 'brand': 'Momo Corner', 'image': 'assets/images/broccoli.png', 'restaurant': 'Momo Corner', 'rating': '4.6', 'time': '15-20 Mins', 'distance': '1.8 km', 'totalSells': '15K+ orders', 'isVeg': true, 'price': 90.0, 'weight': '6 pcs', 'variants': [{'weight': '6 pcs', 'price': 90.0, 'originalPrice': 120.0}, {'weight': '10 pcs', 'price': 130.0, 'originalPrice': 170.0}]},
    {'id': 'r26', 'name': 'Paneer Kurkure Momos', 'brand': 'Momo Corner', 'image': 'assets/images/broccoli.png', 'isBestseller': true, 'restaurant': 'Momo Corner', 'rating': '4.8', 'time': '15-20 Mins', 'distance': '1.8 km', 'totalSells': '22K+ orders', 'isVeg': true, 'price': 140.0, 'weight': '6 pcs', 'variants': [{'weight': '6 pcs', 'price': 140.0, 'originalPrice': 180.0}, {'weight': '10 pcs', 'price': 200.0, 'originalPrice': 250.0}]},
  ],
  'Desserts & Beverages': [
    {'id': 'r27', 'name': 'Sizzling Brownie with Ice Cream', 'brand': 'Cafe Coffee Day', 'image': 'assets/images/broccoli.png', 'isBestseller': true, 'restaurant': 'Cafe Coffee Day', 'rating': '4.7', 'time': '20 Mins', 'distance': '2.5 km', 'totalSells': '18K+ orders', 'isVeg': true, 'price': 250.0, 'weight': '1 Portion', 'variants': [{'weight': '1 Portion', 'price': 250.0, 'originalPrice': 299.0}]},
    {'id': 'r28', 'name': 'Sweet Fresh Lassi', 'brand': 'Punjabi Dhaba', 'image': 'assets/images/broccoli.png', 'restaurant': 'Punjabi Dhaba', 'rating': '4.6', 'time': '40 Mins', 'distance': '3.0 km', 'totalSells': '14K+ orders', 'isVeg': true, 'price': 60.0, 'weight': '1 Glass', 'variants': [{'weight': '1 Glass', 'price': 60.0, 'originalPrice': 80.0}, {'weight': 'Jumbo Glass', 'price': 100.0, 'originalPrice': 130.0}]},
    {'id': 'r29', 'name': 'Hot Chocolate Fudge', 'brand': 'Domino\'s Pizza', 'image': 'assets/images/broccoli.png', 'restaurant': 'Domino\'s Pizza', 'rating': '4.5', 'time': '20-25 Mins', 'distance': '2.1 km', 'totalSells': '28K+ orders', 'isVeg': true, 'price': 129.0, 'weight': '1 Portion', 'variants': [{'weight': '1 Portion', 'price': 129.0, 'originalPrice': 149.0}]},
  ],
};